import { FaAngular, FaAws, FaCss3, FaDocker, FaHtml5, FaJs, FaLaravel, FaLinux, FaNodeJs, FaPhp, FaPython, FaReact, FaVuejs } from "react-icons/fa";
import {
    SiElasticsearch,
    SiGit,
    SiMariadb,
    SiMikrotik,
    SiMongodb,
    SiMysql,
    SiNestjs,
    SiNextdotjs,
    SiPostgresql,
    SiRedis,
    SiMicrosoftsqlserver,
    SiTailwindcss,
    SiTerraform,
    SiTypescript,
} from "react-icons/si";

export const skillIcons = {
    react: FaReact,
    nextjs: SiNextdotjs,
    typescript: SiTypescript,
    javascript: FaJs,
    vue: FaVuejs,
    angular: FaAngular,
    tailwind: SiTailwindcss,
    html: FaHtml5,
    css: FaCss3,
    php: FaPhp,
    laravel: FaLaravel,
    node: FaNodeJs,
    nestjs: SiNestjs,
    python: FaPython,
    mysql: SiMysql,
    mariadb: SiMariadb,
    postgresql: SiPostgresql,
    mongodb: SiMongodb,
    sqlserver: SiMicrosoftsqlserver,
    redis: SiRedis,
    elasticsearch: SiElasticsearch,
    aws: FaAws,
    docker: FaDocker,
    linux: FaLinux,
    terraform: SiTerraform,
    git: SiGit,
    mikrotik: SiMikrotik,
};